name = "training-app"
compatibility_date = "2026-03-02"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "training-app"

[[d1_databases]]
binding = "DB"
database_name = "training-db"
database_id = "e46cef06-95bf-4bca-8e98-409a0d9df008"

[vars]
DATABASE_URL = "file:./dev.db"
